//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leo.ConsoleApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name SayResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Say", ReplyAction="*")]
        Leo.ConsoleApp.ServiceReference1.SayResponse Say(Leo.ConsoleApp.ServiceReference1.SayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Say", ReplyAction="*")]
        System.Threading.Tasks.Task<Leo.ConsoleApp.ServiceReference1.SayResponse> SayAsync(Leo.ConsoleApp.ServiceReference1.SayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Say", Namespace="http://tempuri.org/", Order=0)]
        public Leo.ConsoleApp.ServiceReference1.SayRequestBody Body;
        
        public SayRequest() {
        }
        
        public SayRequest(Leo.ConsoleApp.ServiceReference1.SayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SayRequestBody {
        
        public SayRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayResponse", Namespace="http://tempuri.org/", Order=0)]
        public Leo.ConsoleApp.ServiceReference1.SayResponseBody Body;
        
        public SayResponse() {
        }
        
        public SayResponse(Leo.ConsoleApp.ServiceReference1.SayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SayResult;
        
        public SayResponseBody() {
        }
        
        public SayResponseBody(string SayResult) {
            this.SayResult = SayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Leo.ConsoleApp.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Leo.ConsoleApp.ServiceReference1.WebService1Soap>, Leo.ConsoleApp.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Leo.ConsoleApp.ServiceReference1.SayResponse Leo.ConsoleApp.ServiceReference1.WebService1Soap.Say(Leo.ConsoleApp.ServiceReference1.SayRequest request) {
            return base.Channel.Say(request);
        }
        
        public string Say() {
            Leo.ConsoleApp.ServiceReference1.SayRequest inValue = new Leo.ConsoleApp.ServiceReference1.SayRequest();
            inValue.Body = new Leo.ConsoleApp.ServiceReference1.SayRequestBody();
            Leo.ConsoleApp.ServiceReference1.SayResponse retVal = ((Leo.ConsoleApp.ServiceReference1.WebService1Soap)(this)).Say(inValue);
            return retVal.Body.SayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Leo.ConsoleApp.ServiceReference1.SayResponse> Leo.ConsoleApp.ServiceReference1.WebService1Soap.SayAsync(Leo.ConsoleApp.ServiceReference1.SayRequest request) {
            return base.Channel.SayAsync(request);
        }
        
        public System.Threading.Tasks.Task<Leo.ConsoleApp.ServiceReference1.SayResponse> SayAsync() {
            Leo.ConsoleApp.ServiceReference1.SayRequest inValue = new Leo.ConsoleApp.ServiceReference1.SayRequest();
            inValue.Body = new Leo.ConsoleApp.ServiceReference1.SayRequestBody();
            return ((Leo.ConsoleApp.ServiceReference1.WebService1Soap)(this)).SayAsync(inValue);
        }
    }
}
